### HELLO
GET http://localhost:3000

### USERS
### GET Users
GET http://localhost:3000/users

### GET Users Address
GET http://localhost:3000/users/address?cep=08717380

### POST - Create User
POST http://localhost:3000/users
Content-Type: application/json

{
  "name": "Dev Tedesco"
}

### NOT FOUND
GET http://localhost:3000/login